### ISSUE TITLE
how can i link this package , manual linking steps has not good expression !!

### ISSUE THREAD

**Issue by Moji0098** [githuboftigran/rn-range-slider#16] opened 2019-07-09 14:08 UTC

**Comment by mouveo** [comment] 2019-07-09 14:59
Did you try " react-native link rn-range-slider "?
That works for me...

**Comment by Moji0098** [comment] 2019-07-09 15:01
yes . but it didn't  work !!

**Comment by githuboftigran** [comment] 2019-07-09 15:04
@Moji0098 are you using react native version 0.60?
Facebook changed lot of things in 0.60 and libraries are no longer need to be linked. Instead you need to run pod update for iOS. Didn't try that yet actually, but will do it in weekend.
Please let me know if you solve the issue

**Comment by Moji0098** [comment] 2019-07-09 15:08
no man ,
```
...
    "react": "16.6.3",
    "react-native": "0.57.8",
...
```

i need some code to add to for example **MainActivity** and some other files ... 
help me to add these codes . tnx

**Comment by githuboftigran** [comment] 2019-09-30 11:45
@Moji0098 , I updated this lib, now it has podspec and works with react-native 0.60+
If you still use older version (e.g. 0.57.8) react-native link should work.
Try to unlink -> remove dependency -> add dependency -> link
Closing this issue, as I can't reproduce it.

**Closed by githuboftigran** 2019-09-30 11:45 UTC
