### ISSUE TITLE
There is a way to format the textFormat?

### ISSUE THREAD

**Issue by alecpo** [githuboftigran/rn-range-slider#31] opened 2019-11-08 13:46 UTC
For exemple the value is 500000 and I wanna show "500 thousand" in the label. (value / 1000).

What I mean is: I need a way to get the number of the thumb that I'm currently changing and use this as a parameter inside the textFormat prop. 

So I would be able to show a formatted number and a dynamic complementary string around this number.

**Comment by githuboftigran** [comment] 2019-11-08 14:26
@alecpo , you can't define an executable code on JS side and execute it on native side, `textFormat` is just a simple text formatter which is passed to `String.format` on Android side and `NSString stringWithFormat`.
But you can set min and max to your `maxValue / 1000` and `minValue / 1000` and step to your `step / 1000` and in `onValueChanged` multiply values by 1000 again.

**Comment by alecpo** [comment] 2019-11-08 14:48
@githuboftigran this solve part of my problem but this doesn't allow me to show "thousand" or "million" in the textFormat depending of the scale of my min or maxValue. =/

**Comment by githuboftigran** [comment] 2019-11-08 14:51
@alecpo, you can set `textFormat` to '%d million' or '%d thousand' depending on values. BTW I'd recommend `K` and `M` instead of `thousand` or `million`. That's a better UI :)

**Comment by alecpo** [comment] 2019-11-08 15:00
@githuboftigran But this is the point, how can I get the value to set texFormat depending of something?

should be something like: 

texFormat={value => value > 1000000 ? '%d M' : '%d K'}

but I get the error JSON value '1' of type NSNumber cannot be converted to NSString

**Comment by githuboftigran** [comment] 2019-11-08 15:02
@alecpo , no, `textFormat` prop must be string.
`textFormat={this.state.currentValue > 1000000 ? '%d M' : '%d K'}`

**Comment by alecpo** [comment] 2019-11-08 15:06
> @alecpo , no, `textFormat` prop must be string.
> `textFormat={this.state.currentValue > 1000000 ? '%d M' : '%d K'}`

I think this will not work because I'm using two thumbs for min and max value. If I was using just one thumb this probably would work.

**Comment by githuboftigran** [comment] 2019-11-08 15:13
That's right. In fact I believe it's a better UI/UX to have both values in the same format.
Anyway I'm closing this issue, because this is not a bug or an issue.

**Closed by githuboftigran** 2019-11-08 15:13 UTC
