### ISSUE TITLE
Custom highValue not working on Android

### ISSUE THREAD

**Issue by Saad-Bashar** [githuboftigran/rn-range-slider#4] opened 2019-04-05 04:25 UTC
If I set highValue to 500, the high value is always stuck on 100 in android. iOS works fine.

**Comment by Saad-Bashar** [comment] 2019-04-05 06:58
@githuboftigran , I was going through the java code. I think there is a bug most probably with setting the high value. If you could check that would be really helpful :)

**Comment by githuboftigran** [comment] 2019-04-05 07:00
Thanks for your feedback! Will try to fix this (and other issues) this weekend

**Comment by Saad-Bashar** [comment] 2019-04-05 07:05
Great man! Thanks a lot!

**Comment by Saad-Bashar** [comment] 2019-04-05 07:20
I think I fixed that issue but not sure. I changed this line ` this.highValue = MathUtils.clamp(highValue, lowValue + 1, maxValue);` from this to `this.highValue = highValue >= maxValue ? highValue : maxValue;`

**Comment by githuboftigran** [comment] 2019-04-08 19:14
@Saad-Bashar Could you please show the component JSX?

**Comment by githuboftigran** [comment] 2019-04-08 19:32
Because I couldn't reproduce the issue

**Comment by Saad-Bashar** [comment] 2019-04-10 05:48
Sorry for the late reply, this is what I have:

```
<RangeSlider
                  selectionColor={colors.primary}
                  blankColor={'#DADADA'}
                  style={{ width: width - 100, height: 20 }}
                  labelStyle={'none'}
                  thumbBorderColor={colors.primary}
                  thumbBorderWidth={1}
                  step={50}
                  min={MIN_VALUE}
                  max={MAX_VALUE}
                  highValue={MAX_VALUE}
                  onValueChanged={(minPrice, maxPrice) => {
                    this.setState({
                      minPrice,
                      maxPrice,
                    });
                  }}
                />
```

**Comment by githuboftigran** [comment] 2019-04-10 06:04
highValue prop is the value of higher thumb. You should use this prop if you want to set a the value programmatically. Right now you set it every time view is rerendered and slider renders the higher thumb with that value. So the solution is to remove highValue prop.
I think I need to change the api, because it's a bit confusing.
This is one of my first packages so sorry for these problems :) Will make this slider better once I have time.

Thanks

**Comment by Saad-Bashar** [comment] 2019-04-10 06:09
understood. No worries. So if I want to set the higher thumb to the max value, how can I achieve that?

**Comment by githuboftigran** [comment] 2019-04-10 06:16
That's a good question. And I think I don't have an answer to it right now.
This workaround may work:
```
const highValueProp = isFirstRendering ? {highValue: MAX_VALUE} : {}
...
max={MAX_VALUE}
{...highValueProp}
highValue={MAX_VALUE}
onValueChanged={(minPrice, maxPrice) => {
...
```

I won't close this issue and will leave a comment when I release version 2
Thanks for understanding

**Comment by Saad-Bashar** [comment] 2019-04-10 06:23
Thanks a lot!

**Comment by Vadym-Kyrylenko** [comment] 2019-05-27 14:09
> That's a good question. And I think I don't have an answer to it right now.
> This workaround may work:
> 
> ```
> const highValueProp = isFirstRendering ? {highValue: MAX_VALUE} : {}
> ...
> max={MAX_VALUE}
> {...highValueProp}
> onValueChanged={(minPrice, maxPrice) => {
> ...
> ```
> 
> I won't close this issue and will leave a comment when I release version 2
> Thanks for understanding

Hello! You are not going to release the second version yet?

**Comment by kaytee319** [comment] 2019-05-28 10:12
> That's a good question. And I think I don't have an answer to it right now.
> This workaround may work:
> 
> ```
> const highValueProp = isFirstRendering ? {highValue: MAX_VALUE} : {}
> ...
> max={MAX_VALUE}
> {...highValueProp}
> onValueChanged={(minPrice, maxPrice) => {
> ...
> ```
> 
> I won't close this issue and will leave a comment when I release version 2
> Thanks for understanding

Even this workaround is not setting the initial highValue for android. The initial highValue still remains 100.

**Comment by githuboftigran** [comment] 2019-06-01 09:12
Will change the API a bit today, thanks for waiting!

**Comment by githuboftigran** [comment] 2019-06-02 11:41
Updated the api, added methods to set high and low values.

**Closed by githuboftigran** 2019-06-02 11:41 UTC
