### ISSUE TITLE
Show range numbers

### ISSUE THREAD

**Issue by SmirnovM91** [githuboftigran/rn-range-slider#39] opened 2020-02-08 14:42 UTC
Issue #15 fixes only one part of this problem. I need to see 2 labels instead of one in range slider. But it is showing only the highest value.

Do you have any ideas how to fix it?

![image](https://user-images.githubusercontent.com/32675072/74087112-889fd900-4ab3-11ea-9e9e-cc2d39635aae.png)

**Comment by githuboftigran** [comment] 2020-02-08 14:56
@SmirnovM91 , this is a duplicate of [this issue](https://github.com/githuboftigran/rn-range-slider/issues/35):
So closing this one too.

**Closed by githuboftigran** 2020-02-08 14:56 UTC

**Comment by githuboftigran** [comment] 2020-02-08 15:12
@SmirnovM91 , that's a bad UX. Please check out this particular [comment](https://github.com/githuboftigran/rn-range-slider/issues/15#issuecomment-510420588)
